### ISSUE TITLE
control/Graticule.d.ts defines setStyle() incorrectly

### ISSUE THREAD

**Issue by mflorence99** [Siedlerchr/types-ol-ext#100]
`control/Graticule.d.ts` defines `setStyle()` with no parameters:

```typescript
    /** Set Style
     * @api
     */
    setStyle(): void;
```

Whereas the ol-ext code in `control/Graticule.js` codes it as:

```javascript
  setStyle(style) {
    this._style = style
  }
```

Many thanks for your great work on this project!

**Comment by Siedlerchr** [comment]
Thanks for reporting! Is now fixed in the released version
