### ISSUE TITLE
`options.pattern` is typed incorrectly in both `style/FillPattern.d.ts` and `style/StrokePattern.d.ts`

### ISSUE THREAD

**Issue by mflorence99** [Siedlerchr/types-ol-ext#101]
I believe this is a side-effect of the issue that the types are incorrect in the base `ol-ext` code and that, if corrected there, these files would be generated correctly.

Please see `ol-ext` issue [867](https://github.com/Viglino/ol-ext/issues/867).

**Comment by Siedlerchr** [comment]
Thanks for the hint. I will take a look at it in the next days
