### ISSUE TITLE
Wrong TypeScript-Definition in Dijskra.d.ts

### ISSUE THREAD

**Issue by motto76** [Siedlerchr/types-ol-ext#103]
Hello,

we have been looking into using the Dijkstra algorithm from the ol-ext package and found two errors in its TypeScript definition.

The following two lines should be changed as follows.
Line 9:
From 
`source: Vector<VectorSource<Geometry>>;`
to 
`source: VectorSource<Geometry>`

Line 28:
from 
`@param {Vector} options.source the source for the edges`
to 
`@param {VectorSource} options.source the source for the edges`

Please adjust the definition accordingly.

**Comment by Siedlerchr** [comment]
Thanks for reporting this. I built a new version
