### ISSUE TITLE
Class export in `filter/Colorize.d.ts` and other filters appears incorrect

### ISSUE THREAD

**Issue by mflorence99** [Siedlerchr/types-ol-ext#105]
`ol-ext` exports its `Colorize` filter class as `default`, but the type definition in `filter/Colorize.d.ts` does not.

This pattern is common to ALL the original `ol-ext` filters but the above anomaly is present in the type definitions for:

```
CanvasFilter
Clip
Colorize
Composite
CSS
Lego
PencilSketch
Pointillism
SVGFilter
Texture
```

However, the type definitions for the following correctly export their class:

```
Crop
Fold
Halftone
Mask
Paper
```

In all cases, I believe, the class should be exported like this (`export default ... `):

```typescript
export default class Crop extends Mask { ...}
```

The idea is that the required import statement should not have to change after the type definitions in this package are installed. For example, this now throws a Typescript error:

```typescript
import Colorize from 'ol-ext/filter/Colorize';
```

Interestingly, this can be "fixed" by coding:

```typescript
import { Colorize } from 'ol-ext/filter/Colorize';
```

But that hack triggers another, downstream Typescript error:

```
./lib/src/ol/ol-filter-colorize.ts:18:28-36 - Error: export 'Colorize' (imported as 'Colorize') was not found in 'ol-ext/filter/Colorize' (possible exports: default)
```

**Comment by Siedlerchr** [comment]
Thanks for  mentioning. Normally everything should have a default export. I take a look.

**Comment by Siedlerchr** [comment]
Thanks again.  I published a fixed version now. Also fixed some other issues
