### ISSUE TITLE
'autoClose' does not exist in type 'Options'  on SelectCluster

### ISSUE THREAD

**Issue by Bahaa-Fadhil** [Siedlerchr/types-ol-ext#111]
Hi,

autoClose option missing on SelectCluster method [ol](https://viglino.github.io/ol-ext/doc/doc-pages/ol.html)[.interaction](https://viglino.github.io/ol-ext/doc/doc-pages/ol.interaction.html). SelectCluster

can you add autoClose?: boolean; to[ Options ](https://github.com/Siedlerchr/types-ol-ext/blob/master/%40types/ol-ext/interaction/SelectCluster.d.ts#:~:text=export%20interface%20Options,%7D)

**Comment by Siedlerchr** [comment]
Thanks for the info. I will update  to the new ol-ext version and add the missing property
