### ISSUE TITLE
Missing property in SplitEvent definition

### ISSUE THREAD

**Issue by MrBazlow** [Siedlerchr/types-ol-ext#118]
Type definition of SplitEvent:

https://github.com/Siedlerchr/types-ol-ext/blob/08dc7aa0df8b9f530b5c8d197f7495352decc7fc/%40types/ol-ext/interaction/Split.d.ts#L88-L94

Does not match implementation of SplitEvent:

https://github.com/Viglino/ol-ext/blob/8e442c4de12b3a1faaba6ffa6cd8dbefa2d48315/src/interaction/Split.js#L243-L258

Property "toSplit" should be "features"

![image](https://user-images.githubusercontent.com/67396813/214868939-b27e851d-71d9-4f35-af20-24b8c7457a7c.png)

**Comment by Siedlerchr** [comment]
Thanks! Fixed now
