### ISSUE TITLE
conflict jsdoc and typescript

### ISSUE THREAD

**Issue by 209** [Siedlerchr/types-ol-ext#119]
Anotation @param use only for function. 
When we use @construct and @param:

<img width="985" alt="Снимок экрана 2023-03-14 в 23 27 37" src="https://user-images.githubusercontent.com/4629854/225128674-eef78457-9e8e-41d2-8c6d-c4232c2ad147.png">

Correct way:
<img width="975" alt="Снимок экрана 2023-03-14 в 23 28 17" src="https://user-images.githubusercontent.com/4629854/225128706-bc78934d-47e9-424b-ad4e-64fbb331e934.png">

**Comment by Siedlerchr** [comment]
Freel free to create a PR

**Comment by 209** [comment]
@Siedlerchr no problem. https://github.com/Siedlerchr/types-ol-ext/pull/120
