### ISSUE TITLE
Crop filters Options lacks wrapX

### ISSUE THREAD

**Issue by theheckwr** [Siedlerchr/types-ol-ext#129]
The resolution of this issue https://github.com/Viglino/ol-ext/issues/657 suggests using `wrapX` in the options.
While this works, it leads to an issue with the typing.
![image](https://github.com/Siedlerchr/types-ol-ext/assets/22587394/b66d0898-592e-48f3-bc3f-77eb4ac22e3f)
![image](https://github.com/Siedlerchr/types-ol-ext/assets/22587394/f4ebad7f-f7c5-48ba-85df-2c7ac07d7bd3)

If I can help with testing or further infos, let me know.

**Comment by theheckwr** [comment]
I'm sorry, it's there, my sourcecode got messed up and I didn't recognize it.

**Comment by Siedlerchr** [comment]
I was just about to look into it and wondered where the issue went 😆  But if you notice any other issues, just report.

**Comment by theheckwr** [comment]
Sorry for the inconvenience! :see_no_evil: 
Thanks, will do, but looks good so far.
