### ISSUE TITLE
Property name mispelled

### ISSUE THREAD

**Issue by GoutaamT** [Siedlerchr/types-ol-ext#135]
@Siedlerchr 

![image](https://github.com/Siedlerchr/types-ol-ext/assets/109960252/1bfd061a-7889-4651-afdb-2ed1edefbc89)

 **onClose** should be actually **onclose** in line with property defined in Popup Class

**Comment by Siedlerchr** [comment]
Thanks for the hint! Feel free to create a PR to fix this
