### ISSUE TITLE
PrintOptions size must be an array of number

### ISSUE THREAD

**Issue by ltt2801** [Siedlerchr/types-ol-ext#140]
https://github.com/Siedlerchr/types-ol-ext/blob/33ffbc19bcb30bb67a3a816724206ed827f51a32/%40types/ol-ext/control/Print.d.ts#L17C3-L17C3

Hi, size prop is not a boolean type. It must be a number[]

**Comment by Siedlerchr** [comment]
Oh thanks, yes, feel free to create a PR to change that
