### ISSUE TITLE
type Glyph of FontSymbol?

### ISSUE THREAD

**Issue by flyisland** [Siedlerchr/types-ol-ext#156]
1. In the file https://github.com/Siedlerchr/types-ol-ext/blob/master/%40types/ol-ext/style/FontSymbol.d.ts, we have the below type Glyph:

```ts
export interface Glyph {
  font: string,
  char: number,
  theme: string,
  name: string,
  search: string
}
```

2. But the https://github.com/Viglino/ol-ext/blob/master/src/style/FontMakiDef.js and https://github.com/Viglino/ol-ext/blob/master/src/style/FontMaki2Def.js do not match the type of glyph. For example, these two files are missing the "char" key.

**Comment by Siedlerchr** [comment]
Hm, this is odd. Maybe we can simply make all params as optional
