### ISSUE TITLE
Wrong type for options passed in the constructor of GeoImageLayer

### ISSUE THREAD

**Issue by javier-lopez-1s** [Siedlerchr/types-ol-ext#159]
Hi Christoph,

I believe the constructor of the class `GeoImageLayer` should be defined as follows:
`constructor(options?: Options<ImageSource>);`

If that is correct, then the import
`import type { Image } from 'ol/source';`
should be replaced with
`import type { Options } from 'ol/layer/BaseImage';`

Thanks,
Javier

**Comment by Siedlerchr** [comment]
Fixes in #163
