### ISSUE TITLE
The class GeoImage is missing the method getExtent()

### ISSUE THREAD

**Issue by javier-lopez-1s** [Siedlerchr/types-ol-ext#162]
Hi Christoph,

The class `@types/ol-ext/source/GeoImage.d.ts` is missing the method `getExtent()`.

Thanks

**Comment by Siedlerchr** [comment]
Thanks for the reports, I will try to update it in the next days

**Comment by javier-lopez-1s** [comment]
> Thanks for the reports, I will try to update it in the next days

Thanks for the quick response. I can confirm that issues #158, #159, #160, #161 and #162 are now fixed.
