### ISSUE TITLE
The property 'imageMask' should be optional in the constructor of GeoImage

### ISSUE THREAD

**Issue by javier-lopez-1s** [Siedlerchr/types-ol-ext#165]
Hi Christoph,

I believe that in the options passed to the constructor of `@types/ol-ext/source/GeoImage.d.ts` the property `imageMask` should be optional too, like the rest of options. Otherwise you are forced to define a mask, and if you pass an empty array then no image is displayed.

Thanks!
Javier

**Comment by Siedlerchr** [comment]
Thanks for the hint, feel free to create a PR with changes

**Comment by javier-lopez-1s** [comment]
> Thanks for the hint, feel free to create a PR with changes

PR created. Thanks.

**Comment by Siedlerchr** [comment]
I will try to make a new release in the next days

**Comment by Siedlerchr** [comment]
Thanks for reminding me, I just published a new version with your fixes! I totally forgot it

**Comment by javier-lopez-1s** [comment]
> Thanks for reminding me, I just published a new version with your fixes! I totally forgot it

Many thanks!
