### ISSUE TITLE
Add missing types for cspline

### ISSUE THREAD

**Issue by Siedlerchr** [Siedlerchr/types-ol-ext#43]
Declaration needs to be merged with the one for geometry

**Comment by espejor** [comment]
I have this problem and can you give me a short explanation of how to do that?
Thanks.
I have installed in the @types folder and precisely the Cspline.d.ts file is the only one that does not appear in the list of files in the render folder.
There is also no installation error for that file.
I do not know what is the problem

I'm using Angulat and TS

**Comment by Siedlerchr** [comment]
Well, this library does not yet contain type definitions for Cspline. You can do a Pull Request.
Basically, we need to add type definition to Cspline.
Add a new ts file in the render folder with the same name as in ol-ext and add the type signature for the Cspline function. 
Maybe add a test.
I will take a look at it maybe this evening

**Comment by espejor** [comment]
Thanks for your quickly replay. I will try that

**Comment by Siedlerchr** [comment]
@espejor  I've published a new npm version 1.5.1 which now includes the types for CSpline

**Comment by sanak** [comment]
@espejor I am not familiar with Windows + Node.js environment, but if you have `package.json` on your working folder, could you share (paste) what package is actually used around `ol-ext` (or maybe `openlayers-ext`) in the file ?

**Comment by espejor** [comment]
For now it seems that it accepts the import of the module. See if the function works. Thanks for your hard work. I have deleted the previous comment

**Comment by espejor** [comment]
Ok, I am trying to test the latest modification (v 1.5.1). I can perfectly write the code without getting any compiler errors, but trying to execute the code returns the following error:

_**Module not found: Error: Can't resolve 'ol-ext / render / Cspline'** in 'C: \ Users \ mirror \ OneDrive \ Documents \ Angular \ OpordEasy \ src \ app \ entities'_

This is my code


_import ol_coordinate_cspline from "ol-ext/render/Cspline";
...
var coords:Coordinate[] = ol_coordinate_cspline(f.getGeometry().getCoordinates())
..._

**Comment by sanak** [comment]
@espejor  
Okay, but I couldn't reproduce such error on macOS environment.
https://github.com/Siedlerchr/types-ol-ext/pull/71#issuecomment-988827812

I guess that your Angular environment is something specific, so could you provide the following more information ?
> if you have package.json on your working folder, could you share (paste) what package is actually used around ol-ext (or maybe openlayers-ext) in the file ?

Also, if your setup has `webpack.config.js` file, that information is also helpful.

**Comment by sanak** [comment]
@espejor Okay.
By the way, is above error happen on the following your repository ?
https://github.com/espejor/OpordEasy

If so, is it possible to push your working branch ?

**Comment by Siedlerchr** [comment]
@espejor  Try to add it only to the dev dependencies. I tested it with an angular ionicc app and it works fine
check your tsconfig if you have     "allowSyntheticDefaultImports": true .

**Comment by espejor** [comment]
> @espejor Okay. By the way, is above error happen on the following your repository ? https://github.com/espejor/OpordEasy
> 
> If so, is it possible to push your working branch ?

Of course, but let me clean some errors and I'll upload it

**Comment by espejor** [comment]
> @espejor Try to add it only to the dev dependencies. I tested it with an angular ionicc app and it works fine check your tsconfig if you have "allowSyntheticDefaultImports": true .
> 
> And in my tsconfig I have as well;
> 
> ```
>   "paths": {
>       "ol": ["node_modules/@types/ol"],
>       "ol/*": ["node_modules/@types/ol/*"]
>     
> ```

- Deleted dependencies and left only in dev dependencies
- allowSyntheticDefaultImports": true (was true, before)
- Added path in tsconfig.json file.

But doesn't work,
I've included both path entries copying the style for **ol** and **ol/*** but for **ol-ext** 
```
      "ol-ext": ["node_modules/@types/ol-ext"],
      "ol-ext/*": ["node_modules/@types/ol-ext/*"]
```

But unfortunately it doesn't work either

**Comment by sanak** [comment]
@espejor 
> Of course, but let me clean some errors and I'll upload it

Okay.
By the way, I tried the following operation on my macOS environment from your repository's `master` branch, and I couldn't reproduce the issue, so I guess that it is Windows environment specific issue or your current working branch issue.

1. Setup environment with types-ol-ext.
   ```bash
   $ git clone git@github.com:espejor/OpordEasy.git
   $ cd OpordEasy
   $ npm i
   $ npm i -D @types/ol-ext@npm:@siedlerchr/types-ol-ext
   ```
2. Edit some menu (to debug this issue).
   ```diff
   --- a/src/app/components/nav/floating-menu/floating-menu.component.ts
   +++ b/src/app/components/nav/floating-menu/floating-menu.component.ts
   @@ -1,5 +1,7 @@
    import { Component, EventEmitter, OnInit, Output } from '@angular/core';
    import { OperationsService } from 'src/app/services/operations.service';
   +import { Coordinate } from 'ol/coordinate';
   +import ol_coordinate_cspline from "ol-ext/render/Cspline";
    
    @Component({
      selector: 'app-floating-menu',
   @@ -16,6 +18,9 @@ export class FloatingMenuComponent implements OnInit {
    
    
    changeView(){
   +  const coords: Coordinate[] = [[0, 0], [10, 10]];
   +  console.log(ol_coordinate_cspline(coords));
   +
      this.operationsService.activatedOperationsFormOpened = !this.operationsService.activatedOperationsFormOpened
      const data = this.operationsService.activatedOperationsFormOpened?"activated":"deactivated"
      this.emitter.emit(data);
   ```
3. Lauch the server.
   ```bash
   $ npx ng serve
   ```
4. Click the right top 3 bars menu and check browser console log.  
   <img width="891" alt="opordeasy-cspline-console-log" src="https://user-images.githubusercontent.com/629923/145490016-28342996-85d1-4a11-986e-d198eb6edef0.png">

**Comment by espejor** [comment]
Thanks. 
I uninstalled the package and reinstalled it, but it still doesn't work. This problem only appears with this package. maybe it's a windows problem

**Comment by sanak** [comment]
@espejor Well, I tried the same operation (https://github.com/Siedlerchr/types-ol-ext/issues/43#issuecomment-990389122) on my desktop Windows 10 + node-v16.13.1 with chocolatey environment, but I couldn't reproduce the issue.

Anyway, if you push the working branch, let me know about it.
(It may be better to use your repository's issue than here, because now I think that the cause is in your repository's specific setting.)

**Comment by espejor** [comment]
Done 
_https://github.com/espejor/OpordEasy_

**Comment by sanak** [comment]
@espejor Okay. I could reproduce the issue on my macOS environment with changing the following diff...
Let me check what is the actual cause...
```diff
--- a/src/app/entities/entity-line.class.ts
+++ b/src/app/entities/entity-line.class.ts
@@ -62,7 +62,7 @@ export class EntityLine<GeomType extends Geometry = Geometry> extends Entity{
     this.lineOptions = lineOptions;
 
     if (this.smooth){
-      // this.setCoordinates(ol_coordinate_cspline(this.getCoordinates()))
+      this.setCoordinates(ol_coordinate_cspline(this.getCoordinates()))
     }
 
     if(lineOptions){
@@ -97,7 +97,7 @@ export class EntityLine<GeomType extends Geometry = Geometry> extends Entity{
       return styles
     }
 
-    // this.getGeometry().cspline()
+    this.getGeometry().cspline()
```

**Comment by sanak** [comment]
@espejor Oh, you haven't installed `ol-ext`, yet.
Just executing `npm i -D ol-ext` solved the issue. 😄

**Comment by espejor** [comment]
> @espejor Oh, you haven't installed `ol-ext`, yet. Just executing `npm i -D ol-ext` solved the issue. 😄

Ok, thanks, it works fine. I removed the ol-ext package as well as every instance of ol-ext, such as @type/ol-ext, and I forgot to reinstall it
