### ISSUE TITLE
Release current master

### ISSUE THREAD

**Issue by msmid** [Siedlerchr/types-ol-ext#45]
Hello @Siedlerchr 

Do you think it is possible to release current master? We would love to use the [AnimatedCluster.d.ts](https://github.com/Siedlerchr/types-ol-ext/blob/master/%40types/ol-ext/layer/AnimatedCluster.d.ts) definition which was recently added and it is not published on npm yet.

Thank you for your great job.

**Comment by sanak** [comment]
@Siedlerchr @msmid  
Well, I have one pending PR (#44), but I become a bit busy in this week, so I will send it as it is...

For next release, I think that continuous release will be possible (like original `ol-ext` 😄 ).

**Comment by msmid** [comment]
Awesome @sanak , thank you a lot 👍

**Comment by timowolf** [comment]
Great, this is nice

**Comment by sanak** [comment]
@Siedlerchr Yes, I think that the PR is okay to be merged.

@msmid I forgot to ask you, but is it better for me to add https://viglino.github.io/ol-ext/examples/animation/map.animatedcluster.html examples to this types-ol-ext repository ?
If so, I will try to check that quickly.

**Comment by msmid** [comment]
I think it is not super important, ol-ext docs/examples are still available to everybody 🙂

**Comment by timowolf** [comment]
I agree here. I would prefer to have a fast release. 👍

**Comment by sanak** [comment]
@msmid @timowolf  
Okay, thanks for confirmation!

@Siedlerchr
>> Should I merge your PR then before a release? Then I can do npm publish tonight

I replied the following, but let me check the other Search classes quickly (in 1 hour).
> Yes, I think that the PR is okay to be merged.

**Comment by sanak** [comment]
@Siedlerchr Oh, it's merged. 😄  Then, no problem.

**Comment by Siedlerchr** [comment]
Oh sorry ;) Just released https://www.npmjs.com/package/@siedlerchr/types-ol-ext 
1.1.0
If you find any problems please open an issue or a PR°!

**Comment by sanak** [comment]
Okay, thanks! 👍
