### ISSUE TITLE
TS2688: Cannot find type definition file for 'ol-ext'

### ISSUE THREAD

**Issue by sanak** [Siedlerchr/types-ol-ext#47]
When building embedded examples, there is no error, but when I build [redmine_gtt](https://github.com/gtt-project/redmine_gtt) plugin, it shows the following error.
```
ERROR in /Users/sanak/Desktop/redmine_gtt/tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'ol-ext'.
  The file is in the program because:
    Entry point for implicit type library 'ol-ext'
```

And after creating empty `types.d.ts` file in the root directory, then this error disappeared.

Here are the steps to reproduce.
```bash
$ git clone git@github.com:gtt-project/redmine_gtt.git -b feature/upgrade-types-ol-ext
$ cd redmine_gtt
$ yarn
$ npx webpack
:
ERROR in /Users/sanak/Desktop/redmine_gtt/tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'ol-ext'.
  The file is in the program because:
    Entry point for implicit type library 'ol-ext'

webpack 5.24.4 compiled with 1 error in 12085 ms
```

```bash
$ touch node_modules/@types/ol-ext/types.d.ts
$ npx webpack
:
webpack 5.24.4 compiled with 3 warnings in 11320 ms
```

@Siedlerchr  
I set the entry point to `types.d.ts` in #13, because there was the file at that time,
- https://github.com/Siedlerchr/types-ol-ext/pull/13/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

but `types-ol` is using `index.d.ts` (default), so, I am thinking to change `package.json` as follows,
```diff
- "types": "types.d.ts",
+ "types": "index.d.ts",
```
then add empty `index.d.ts` file, but is this okay ?

**Comment by Siedlerchr** [comment]
Thanks, might also be the case that we need to add all other files as exports 
If this works with an empty file then go ahead for the moment

**Comment by sanak** [comment]
Okay, sure.
Thanks for confirmation!
