### ISSUE TITLE
Exampel of use

### ISSUE THREAD

**Issue by psilvao** [Siedlerchr/types-ol-ext#5]
Hi 

  Thanks for your contribution, i'm newbie in ol-ext and nodejs, so i was programming with parcel an example of search for nominatim witl the library ol-ext , but i found the following error, in that case , how i can use yur code for to solve that trouble?

  Thanks in advance,
  Pablo

![image](https://user-images.githubusercontent.com/2114081/88054905-1f28f980-cb2c-11ea-9d9b-12d3007596bf.png)

**Comment by Siedlerchr** [comment]
Hi,
thanks for your interest. The error is just a hint. Currently there are not yet any type definitons for ol-ext avaiable. This project aims to change that, however, it's not yet ready

**Comment by psilvao** [comment]
Hmm What a pity, do you have some instructions to solve this problem? So I
investigate on my part.

**Comment by sanak** [comment]
Hi @psilvao,

I added some examples from original `ol-ext`, so you can check the following examples development instruction.
- [examples/README.md](https://github.com/Siedlerchr/types-ol-ext/blob/master/examples/README.md)

I am thinking to add the following Nominatam example at this weekend.
- https://viglino.github.io/ol-ext/examples/search/map.control.searchnominatim.html

**Comment by sanak** [comment]
Well, I checked Nominatim examples on #44 working branch.  
I will check (port) other search examples on that branch (probably at tomorrow).

**Comment by Siedlerchr** [comment]
Cool. That's really good, there are cases where it's hard to find the right type
