### ISSUE TITLE
Vector3D error

### ISSUE THREAD

**Issue by GiannisTsim** [Siedlerchr/types-ol-ext#52]
I am getting the following error when I try to add a Vector3D layer to my map: 

`Argument of type 'Vector3D' is not assignable to parameter of type 'BaseLayer'.
  Type 'Vector3D' is missing the following properties from type 'BaseLayer': on, once, un, className_, and 52 more.ts(2345)`

I am importing Vector3D as `import { Vector3D } from "ol-ext/source/Vector3D";` and use the map's `addLayer` method.

**Comment by Siedlerchr** [comment]
Thanks for the hint, it's missing in the type def.! I will add it
