### ISSUE TITLE
Crop/Mask filter example doesn't work with error

### ISSUE THREAD

**Issue by sanak** [Siedlerchr/types-ol-ext#54]
Here is the error message on Chrome DevTools Console.
```
map.filter.crop.ts:28 Uncaught TypeError: Crop_1.Crop is not a constructor
    at map.filter.crop.ts:28
    at map.filter.crop.ts:54
    at map.filter.crop.ts:54
```

Probably, this issue relates with default export class things at https://github.com/Siedlerchr/types-ol-ext/pull/53

Other examples seem to be no problem.

**Comment by Siedlerchr** [comment]
Thanks for spotting, yep, is missing a default export.
`export class Crop extends Mask {`
should be export default class Crop extends Mask {

**Comment by sanak** [comment]
@Siedlerchr Okay, I will check it quickly.
