### ISSUE TITLE
Question: types-ol-ext 1.0.0 vs 1.0.5

### ISSUE THREAD

**Issue by smellman** [Siedlerchr/types-ol-ext#7]
npm version is 1.0.0 https://github.com/Siedlerchr/types-ol-ext/blob/master/package.json#L3
npm.js package version is 1.0.5 https://www.npmjs.com/package/types-ol-ext

Which is correct?
I want to contribute this project so I want to know current in this repository.

**Comment by Siedlerchr** [comment]
Hi, thanks for your interest. Good question, I didn't create the npm package, so I don't know why it is newer.

**Comment by smellman** [comment]
OK, I see.
I submit [the PR for ol-ext project](https://github.com/Viglino/ol-ext/pull/580) to fix some JSDoc.
After the PR merged, I try to create fixed version.
Thanks!
