### ISSUE TITLE
The definition of the option of GridReference is different from the definition of ol-ext example..

### ISSUE THREAD

**Issue by logue** [Siedlerchr/types-ol-ext#73]
https://github.com/Siedlerchr/types-ol-ext/blob/fe95382bde67492a11f54efca23afd5e0e62718c/%40types/ol-ext/control/GridReference.d.ts#L19-L30

* The first letter of extent and size is capitalized.
* sortFeature is defined as required.

the [ol-ext's example code](https://viglino.github.io/ol-ext/examples/canvas/map.control.gridreference.html) is follows:
```
// New control
ref = new ol.control.GridReference({
  extent: [ -550000, 5250000, 850000, 6650000 ], // <- extent is Extent.
  size: [10,12],
  target: document.querySelector(".options div"),　// <- By definition, only a single DOM is to be selected, but the ol-ext code can also select multiple DOMs.
  source: vectorSource,
  property: "commune",
  sortFeatures: sort, // <- Not required.
  indexTitle: title
});
map.addControl (ref);
```

Regarding target, I think that this definition is rather correct considering the design concept of OpenLayers...

**Comment by Siedlerchr** [comment]
Thanks! Should be fixed now
