### ISSUE TITLE
ProgressBar control issue

### ISSUE THREAD

**Issue by ivayloatns87** [Siedlerchr/types-ol-ext#75]
Hi there,

I think that ProgressBar should accept multiple Tile Layers.

export interface Options extends ControlOptions {
    className?: string;
    label?: string;
    layer?: Layer
}

export interface Options extends ControlOptions {
    className?: string;
    label?: string;
    layers?: Layer[]
}

![Screenshot 2022-01-19 at 13 55 48](https://user-images.githubusercontent.com/32465987/150125210-32218e65-2671-47e9-8838-52ec5c352ffc.png)

Best Regards,

Ivaylo

**Comment by Siedlerchr** [comment]
Thanks, will try to update this in the next days!
