### ISSUE TITLE
No exported members

### ISSUE THREAD

**Issue by sik0vny** [Siedlerchr/types-ol-ext#88]
Am I doing something wrong or is your library missing something?

`ERROR in node_modules/@types/ol-ext/control/GeoBookmark.d.ts(6,10): error TS2305: Module '"/node_modules/@types/ol/ObjectEventType"' has no exported member 'Types'.
node_modules/@types/ol-ext/control/GeoBookmark.d.ts(7,10): error TS2305: Module '"/node_modules/@types/ol/Observable"' has no exported member 'CombinedOnSignature'.
node_modules/@types/ol-ext/control/GeoBookmark.d.ts(7,31): error TS2305: Module '"/node_modules/@types/ol/Observable"' has no exported member 'EventTypes'.
node_modules/@types/ol-ext/control/GeoBookmark.d.ts(7,43): error TS2305: Module '"r/node_modules/@types/ol/Observable"' has no exported member 'OnSignature'.

**Comment by Siedlerchr** [comment]
Hi, I am trying to look into it. Can you give me a usage example? e..g Where you used that or where does the warning come from?
