### ISSUE TITLE
 Class constructor Control cannot be invoked without 'new'     at ol_control_SearchNominatim.ol_control_Search

### ISSUE THREAD

**Issue by TiDaGo** [Siedlerchr/types-ol-ext#94]
Uncaught TypeError: Class constructor Control cannot be invoked without 'new'
    at ol_control_SearchNominatim.ol_control_Search [as constructor] (Search.js:197:62)
    at ol_control_SearchNominatim.ol_control_SearchJSON [as constructor] (SearchJSON.js:43:51)
    at new ol_control_SearchNominatim (SearchNominatim.js:44:55)
    
Hi im not understand where problem :-) or in my code, or in ol-ext, or in your.

im use TS 

package.json
```
    "ol": "^7.1.0",
    "ol-ext": "^3.2.30",
    "@types/ol-ext@npm:@siedlerchr/types-ol-ext": "2.3.0"
```

THX

**Comment by Siedlerchr** [comment]
@TiDaGo  Thanks for reporting, ol-ext and the types therefore are not yet compatible with OpenLayers version 7 and later.
https://github.com/Viglino/ol-ext/issues/839

**Comment by TiDaGo** [comment]
O! Realy! Thx, plz upd your read.me file - its save your time )

**Comment by TiDaGo** [comment]
O! Realy !! thx,

Plz update your read.me file )


*Best regards Gosha*
*C# Developer*
*Whatsapp*

*, Viber +7 977 894 6742Telegram: @KroGosSerbija tel: +381 61 658 2544*


сб, 3 сент. 2022 г. в 20:24, Christoph ***@***.***>:

**Comment by Siedlerchr** [comment]
The current version of ol-ext is compatible with ol7 and so are the types
