### ISSUE TITLE
Wrong type in Transform interaction method

### ISSUE THREAD

**Issue by GastonZalba** [Siedlerchr/types-ol-ext#98]
The `style` type in the `setStyle` method of the Transform interaction is wrong. Now is [Style](https://openlayers.org/en/latest/apidoc/module-ol_style_Style-Style.html), but it should be: `'default'|'translate'|'rotate'|'rotate0'|'scale'|'scale1'|'scale2'|'scale3'|'scalev'|'scaleh1'|'scalev2'|'scaleh3'`

The [original](https://github.com/Viglino/ol-ext/blob/master/src/interaction/Transform.js#L214) jsDoc is:
`@param {style} style Style name: 'default','translate','rotate','rotate0','scale','scale1','scale2','scale3','scalev','scaleh1','scalev2','scaleh3'`

**Comment by Siedlerchr** [comment]
Thanks for reporting! I created a fix and will publish a new version then
